### ISSUE TITLE
Bewerbung von ZawakoYonshi, als Architekt

### ISSUE THREAD

**Issue by ZawakoYonshi** [csBlackWolf/minefox.fun#12]
Vorrausetzung für eine Bewerbung bei unseren Team ist, das du auf den Minecraft-Server Minefox.FUN aktuell den VIP-Status hast.

Wenn du bereits VIP bist, beantworte bitte folgende Fragen:

**Wer bist du? (Kurze Vorstellung und dein Ingame-Name)**
Guten tag, 
ich heiße ZawakoYonshi und spiele seit dem der Server eröffnet wurde darauf.

**Warum willst du Teil des Teams werden?**
Ich möchte ein teil des Teams werden da mir der Server sehr gut gefällt und ich zu seinem erfolg 
beitragen möchte.

**Was denkst du, kannst du zum Team beitragen?**
Ich bin sehr Kreativ und Baue sehr gern aus dem Grund bewerbe ich mich auch als Architekt, wie 
auf dem letzten Server habe ich mir dinge überlegt was man bei Events zbs. Weihnachten oder Silvester auf dem Server veranstalten kann. Ich baue sehr gerne für Event und Feiertage dinge wie Raketen anlagen oder riesige Statuen.

**Hast du sonst noch etwas hinzuzufügen?**

**Comment by csBlackWolf** [comment]
Der Aufnahme von ZawakoYonshi in das Team wurde per Voting zugestimmt!

Willkommen im Team. 🎉
Eine entsprechende Gruppe für dich wird noch extra angelegt.

![grafik](https://user-images.githubusercontent.com/30509936/80314769-b44d7800-87f3-11ea-93d2-80683442caa5.png)
