### ISSUE TITLE
Freischaltung

### ISSUE THREAD

**Issue by FarlontheWoof** [csBlackWolf/minefox.fun#13]
Notwendige Frage:
** Wie lautet dein aktueller Minecraft Benutzername? **
Farlon_
** Wie hast du von Minefox.FUN erfahren? **
Hab früher schon drauf gespielt 
** Wie lange ungefähr spielst du schon Minecraft? **
Lange

**Comment by csBlackWolf** [comment]
Du wurdest freigeschaltet.
Viel Spaß auf Minefox.FUN 👍
