### ISSUE TITLE
Freischaltung

### ISSUE THREAD

**Issue by natschi89** [csBlackWolf/minefox.fun#14]
Notwendige Frage:
** Wie lautet dein aktueller Minecraft Benutzername? **
natschi89
** Wie hast du von Minefox.FUN erfahren? **
durch csBlackWolf
** Wie lange ungefähr spielst du schon Minecraft? **
keine Ahnung

**Comment by csBlackWolf** [comment]
Freigeschaltet.
Viel Spaß!
