### ISSUE TITLE
Freischaltung

### ISSUE THREAD

**Issue by SirChristopherus** [csBlackWolf/minefox.fun#18]
Bitte beantworte die folgenden Fragen:

**Wie lautet dein aktueller Minecraft Benutzername?**
SirChristopher
**Wie hast du von Minefox.FUN erfahren?**
Zawakos Instagram
**Wie lange ungefähr spielst du schon Minecraft?**
8 Jahre

**Comment by csBlackWolf** [comment]
Du wurdest freigeschaltet. Viel Spaß auf Minefox.FUN 🐺
