### ISSUE TITLE
Wiederherstellung

### ISSUE THREAD

**Issue by MusjeHenryBlue** [csBlackWolf/minefox.fun#19]
Die Wiederherstellung nach verlust von Erfahrungspunkten/Level, Gegenständigen und anderen ist nur möglich, wenn der Verlust oder Schaden mit einen Bug oder ein Griefing-Vorfall zusammenhängt. Hängt die Anfrage mit einen Bug zusammen muss für den bereits ein offenes Ticket besteht oder neu erstellt werden und auf das betreffende Ticket verwiesen werden.

** Diese Daten benötigen wir für die Wiederherstellung **

- Was soll wiedergestellt werden oder ging verloren?
 Exp vom Ender Dragon

- Aktueller Minecraft-Benutzername des betreffenden Accounts
Henry_Blue

- Zeitpunkt des Vorfalls
19  Uhr

(Nur bei Verlust der vermutlich durch ein Bug ausgelöst wurde)
- Link oder ID vom zugehörigen Ticket des betreffenden Bug's

**Comment by csBlackWolf** [comment]
Da ich mal da von ausgehe das der Verlust durch ein Bug entstanden ist, benötige ich bitte noch ein dazu passenden Bug-Report damit ich das nachvollziehen kann und der Fehler möglichst nicht noch einmal auftritt.

So bald ich das habe, werde ich das ticket weiter bearbeiten.

Vielen Dank.

# 
Mit freundlichen Grüßen

csBlackWolf
