### ISSUE TITLE
Plazieren von Schildern

### ISSUE THREAD

**Issue by RhysShepherd** [csBlackWolf/minefox.fun#4]
Beim plazieren von Schildern kommt immer die Meldung
"You dont have the permission to create teleportation signs"
Dies tritt scheinbar nur auf mit User rechten
![2019-03-18_22 02 47](https://user-images.githubusercontent.com/48696606/54564127-4d904500-49cb-11e9-8765-223d9dcf7909.png)

**Comment by csBlackWolf** [comment]
Schaue ich mir mal übers Wochenende an.
